apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nwu-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/limit-rps: "5"
spec:
  tls:
  - hosts:
    - api.nwu-protocol.com
    secretName: nwu-tls
  rules:
  - host: api.nwu-protocol.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
